[project]
name = "fastapi-and-rabbit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kurosovaya", email = "nonickk9@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=10.0.1",
    "debugpy>=1.8.21",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "pika>=1.4.4",
    "prometheus-client>=0.26.0",
    "prometheus-fastapi-instrumentator>=8.1.0",
    "pymongo>=4.17.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
fastapi-and-rabbit = "fastapi_and_rabbit:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
